plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - data_utility_and_fidelity.md
  - evaluation_setups.md
  - evaluation_results.md
  - evaluation_conclusions.md
  - issues_existing_repos.md
